name: 02 - Workflow Events

on: 
    workflow_dispatch:



jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
    - name: Show the trigger event
      run: echo "The trigger event was ${{ github.event_name }}"
